### ISSUE TITLE
ERROR: Not all intervals have the same length

### ISSUE THREAD

**Issue by gianfilippo** [kundajelab/ChromDragoNN#6] opened 2020-06-30 18:46 UTC
Hi,

I am trying to test your algorithm.

I downloaded the data from the links you provide, and I am starting with the command you provide:
python ./preprocess/make_accessibility_joblib.py --input /path/to/accessibility/file.tsv.gz --output_dir /path/to/dnase/packbited --genome_fasta /path/to/genome/fasta.fa

I understand that I have to run this command on every single file that is contained in dnase.chr.packbited.tar.gz

I just run it on ENCSR979BPU.Fetal_Kidney.UW_Stam.DNase-seq_rep1-pr.IDR0.1.filt.narrowPeak.gz
using hg38 first and hg19 later.

i get then following error:
PREPROCESS::: Reading file into memory
ERROR: Not all intervals have the same length

Can you please explain what I am missing ?

Thanks

**Comment by gianfilippo** [comment] 2020-06-30 18:52
I am also having a problem with the rna processing. I get
ValueError: could not convert string to float: 'ENST00000373020.4,ENST00000494424.1,ENST00000496771.1'

what version of python should I use ? I am running on 3.7

**Comment by suragnair** [comment] 2020-06-30 19:51
Hi, the first error essentially implies that the widths of your regions in the input file are variable. This is because the input to your machine learning model should have a fixed width. For example here:
```chr    start  end    task1  task2  ...  taskM
chr1   50     1050       0      0           0
chr1   1000   2000       1      0           1
...
chr2   100    1100       1      0           1```

All inputs have a fixed width of 1000bp.

The second error seems to be an issue with formatting. Can you please check it looks like this:
```gene    task1   task2  ...  taskM
MEOX1   3.5189  2.8237      3.7542
SOX8    0.0     0.0         1.9623
...
ZNF195  0.0     0.1232      0.0023```

**Comment by gianfilippo** [comment] 2020-06-30 20:35
HI,

thanks for your prompt reply. I understand the meaning of the errors, what I do not understand is why I am getting these errors using your data

What do you think ?

**Comment by suragnair** [comment] 2020-06-30 22:22
Oh my bad! To run it our data you do not need to preprocess it as it has already been processed. You can simply train:

`python resnet.py -cp /path/to/stage1/checkpoint/dir --dnase /path/to/dnase/packbited --rna_quants /path/to/rna_quants_1630tf.joblib`

**Comment by suragnair** [comment] 2020-07-03 08:39
Hi, does this solve your issue?

**Comment by gianfilippo** [comment] 2020-07-03 13:19
Hi,

this seem to be working but the code fails eventually. It seems that there is an issue with the CUDA driver and PyTorch. The fix is failing and I have to wait for the sys admin to fix it on their end.  Thanks

**Comment by suragnair** [comment] 2020-07-03 23:39
No worries. I'm closing this Issue for now. Feel free to re-open it or open a new Issue if you're stuck!

**Closed by suragnair** 2020-07-03 23:39 UTC

**Comment by gianfilippo** [comment] 2020-09-30 03:43
Hi,

I would like to reopen this issue, as I am trying now to preprocess your peak data files and I am getting the error. How did you reprocess the narrowPeak files to get fixed width of 1000bp ?

i am not familiar with this kind of data, so I may be missing something  here.

Thanks

**Comment by suragnair** [comment] 2020-09-30 07:22
Hi Gianfilippo, from the paper:

"We bin the human genome (GRCh37 assembly) into 200 bp bins (⁠i⁠) every 50 bp. For each of the 123 cellular contexts (⁠j={1…123}⁠), all bins are assigned binary labels (⁠yi,j∈{0,1}⁠) corresponding to accessible (+1) or inaccessible (0) state based on whether they overlap (>50% overlap) context-specific reproducible DNase-seq peaks or not....The cis-regulatory sequence context (Si) for each bin i is represented using 1000 bp of genomic DNA sequence centered at the bin. "

The "context-specific reproducible peaks" would be a set of peaks derived from a peak caller.
